"""create players game_modes matches scores

Revision ID: 047bcca5bc4f
Revises: 
Create Date: 2026-10-09 13:43:21.675273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '047bcca5bc4f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_modes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('game_mode', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_game_modes'))
    )
    op.create_table('players',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nickname', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_players'))
    )
    op.create_table('matches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('player_id', sa.Uuid(), nullable=False),
    sa.Column('game_mode_id', sa.Uuid(), nullable=False),
    sa.Column('idempotency_key', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finish_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('in_progress', 'finished', 'rejected')", name=op.f('ck_matches_status_valid')),
    sa.ForeignKeyConstraint(['game_mode_id'], ['game_modes.id'], name=op.f('fk_matches_game_mode_id_game_modes')),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_matches_player_id_players')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_matches')),
    sa.UniqueConstraint('player_id', 'idempotency_key', name='uq_player_idempotency_key')
    )
    op.create_index('ix_matches_player_started', 'matches', ['player_id', sa.literal_column('started_at DESC'), sa.literal_column('id DESC')], unique=False)
    op.create_table('scores',
    sa.Column('match_id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name=op.f('fk_scores_match_id_matches')),
    sa.PrimaryKeyConstraint('match_id', name=op.f('pk_scores'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scores')
    op.drop_index('ix_matches_player_started', table_name='matches')
    op.drop_table('matches')
    op.drop_table('players')
    op.drop_table('game_modes')
    # ### end Alembic commands ###
